name: CI/CD with Server Deployment

on:
  push:
    branches: [master]  # Триггер на пуш в ветку master [[2]][[5]]

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # [[5]]

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
    
            cd /var/www/frontend || exit 1

            git fetch --all --prune
            git reset --hard origin/master  # Принудительный сброс [[10]]
            git pull origin master

            docker build -t my-frontend .
            docker run -p 8000:3000 my-frontend 
     
